name: Heal
main: Liveset1\Heal\Main
author: Liveset1
verison: 1.0.0
api: 3.0.0

commands:
  Heal:
   description: "Heal yourself!"
   permissions: heal.command
 permissions:
   day.command:
    default: true
  
