name: Heal
main: Heal/Main
author: Liveset1
verison: 1.0
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]

commands:
  Heal:
  description: Heal yourself!
permissions: heal.main.command
  Heal:
  default: false
   description: Allows Player To use /heal
   children:
